package junior.academy.util;

public interface ErrorCodes {
    String NOT_ENOUGH_CHARACTERS="NOT_ENOUGH_CHARACTERS";
    String TOO_MANY_CHARACTERS="TOO_MANY_CHARACTERS";
    String EMPTY="EMPTY_FIELD";
    String WRONG_EMAIL_PATTERN="WRONG_EMAIL_PATTERN";
    String AUTHOR_TOO_YOUNG="AUTHOR_TOO_YOUNG";
    String VALUE_TOO_BIG= "VALUE_TOO_BIG";
    String VALUE_TOO_SMALL = "VALUE_TOO_SMALL";
}
